/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cosc457.finalproject;

import org.apache.commons.io.FileExistsException;
import org.apache.commons.io.FileUtils;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.*;
import java.io.*;
import java.sql.*;
import java.util.*;

/**
 *
 * @author Kevin
 */
public class ABSQuoteFollowUp extends javax.swing.JFrame {

    static final String userName = "jrajew1";//put your MySQL user name
    static final String password = "Cosc*2awc";//put your MySQL password
    Connect connect = new Connect();

    /**
     * Creates new form DBSQuoteFollowUp
     */
    public ABSQuoteFollowUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ABS Quote Follow Up");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Month:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Year:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(132, 132, 132))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Reports().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //gernerate the report 
        try {
            connect.ps = connect.con.prepareStatement("select * from jrajew1db.Customer C, jrajew1db.Quotes Q where C.`Customer#` = Q.`Customer#` and Year(Date)=?;");
            String s1 = jTextField1.getText();
            connect.ps.setString(1, s1);
            connect.res = connect.ps.executeQuery();
            
            

            Workbook wb = new HSSFWorkbook();
            Sheet personSheet = wb.createSheet("TEST");
            Row headerRow = personSheet.createRow(0);
            Cell nameHeaderCell = headerRow.createCell(0);
            Cell addressHeaderCell = headerRow.createCell(1);
        
            int row = 1;
            int row2=0;
            Row dataRow2 = personSheet.createRow(row2);
            Cell dataQuoteCell2 = dataRow2.createCell(0);
            dataQuoteCell2.setCellValue("Customer#");
            Cell dataQuoteaCell2 = dataRow2.createCell(1);
            dataQuoteaCell2.setCellValue("Name");
            Cell dataQuoteaaCell2 = dataRow2.createCell(2);
            dataQuoteaaCell2.setCellValue("QuoteID");
            Cell dataQuoteaaaCell2 = dataRow2.createCell(3);
            dataQuoteaaaCell2.setCellValue("FollowUpDate");
             Cell dataQuoteaaaaCell2 = dataRow2.createCell(4);
            dataQuoteaaaaCell2.setCellValue("Price");
             Cell dataQuoteaaaaaCell2 = dataRow2.createCell(5);
            dataQuoteaaaaaCell2.setCellValue("Awarded");
            
            while (connect.res.next()) {
                //Row dataRow = personSheet.createRow(row);
                //Cell dataNameCell = dataRow.createCell(1);
                /*String quote = connect.res.getString("Count(QuoteID)");
                String name = connect.res.getString("Name");
                String date = connect.res.getString("Date");
                String price = connect.res.getString("Price");
                String FollowUpDate = connect.res.getString("FollowUpDate");
                String open = connect.res.getString("`Open/Closed`");
                String reason = connect.res.getString("Reason");
                String contract = connect.res.getString("ContactLocation");
                String awarded = connect.res.getString("Awarded");*/

                Row dataRow = personSheet.createRow(row);

                Cell dataQuoteCell = dataRow.createCell(0);
                dataQuoteCell.setCellValue(connect.res.getString("Customer#"));
                
                Cell dataaCell = dataRow.createCell(1);
                dataaCell.setCellValue(connect.res.getString("Name"));
                
                Cell dataaaCell = dataRow.createCell(2);
                dataaaCell.setCellValue(connect.res.getString("QuoteID"));
                
                
                Cell dataaaaaCell = dataRow.createCell(3);
                dataaaaaCell.setCellValue(connect.res.getString("FollowUpDate"));
                
                Cell dataaaaaaaaCell = dataRow.createCell(4);
                dataaaaaaaaCell.setCellValue(connect.res.getString("Price"));
                
                Cell dataaaaaaCell = dataRow.createCell(5);
                dataaaaaaCell.setCellValue(connect.res.getString("Awarded"));
                
                /*Cell dataaaaaaCell = dataRow.createCell(4);
                dataaaaaaCell.setCellValue(connect.res.getString("Awarded"));
                
                   Cell dataaaaaaaCell = dataRow.createCell(5);
                dataaaaaaaCell.setCellValue(connect.res.getString("Reason"));
                
                 Cell dataaaaaaaaCell = dataRow.createCell(6);
                dataaaaaaaaCell.setCellValue(connect.res.getString("Price"));
                
                 Cell dataaaaaaaaaCell = dataRow.createCell(7);
                dataaaaaaaaaCell.setCellValue(connect.res.getString("ContractLocation"));
                
                   Cell dataaaaaaaaaaCell = dataRow.createCell(8);
                dataaaaaaaaaaCell.setCellValue(connect.res.getString("Date"));*/
                /*Cell dataDateCell = dataRow.createCell(2);
                dataDateCell.setCellValue(connect.res.getString("Date"));

                Cell dataPriceCell = dataRow.createCell(3);
                dataPriceCell.setCellValue(connect.res.getString("Price"));

                Cell datafollowCell = dataRow.createCell(4);
                datafollowCell.setCellValue(connect.res.getString("FollowUpDate"));

                Cell dataOpenCell = dataRow.createCell(5);
                dataOpenCell.setCellValue(connect.res.getString("`Open/Closed`"));

                Cell dataReasonCell = dataRow.createCell(6);
                dataReasonCell.setCellValue(connect.res.getString("Reason"));

                Cell datacontractCell = dataRow.createCell(7);
                dataReasonCell.setCellValue(connect.res.getString("ContactLocation"));

                Cell dataawardCell = dataRow.createCell(8);
                dataawardCell.setCellValue(connect.res.getString("Awarded"));*/

                row = row + 1;

            }

            FileOutputStream fileOut = new FileOutputStream(new File("ABSQuoteFollowUp"));
            wb.write(fileOut);
            fileOut.close();
            System.out.println("done");

        } catch (Exception e) {
            System.out.println("erorr");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABSQuoteFollowUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABSQuoteFollowUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABSQuoteFollowUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABSQuoteFollowUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABSQuoteFollowUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
/*
try {
            connect.ps = connect.con.prepareStatement("SELECT * FROM CustomerRevenue where Year=?;");
            String s1 = jTextField1.getText();
            connect.ps.setString(1, s1);
            connect.res = connect.ps.executeQuery();

            Workbook wb = new HSSFWorkbook();
            Sheet personSheet = wb.createSheet("TEST");
            Row headerRow = personSheet.createRow(0);
            Cell nameHeaderCell = headerRow.createCell(0);
            Cell addressHeaderCell = headerRow.createCell(1);
            
            int row = 1;
            int row2=0;
            Row dataRow2 = personSheet.createRow(row2);
            Cell dataQuoteCell2 = dataRow2.createCell(0);
            dataQuoteCell2.setCellValue("CustomerNo#");
            Cell dataQuoteaCell2 = dataRow2.createCell(1);
            dataQuoteaCell2.setCellValue("RevenueAmount#");
             while (connect.res.next()) {
                Row dataRow = personSheet.createRow(row);

                Cell dataQuoteCell = dataRow.createCell(0);
                dataQuoteCell.setCellValue(connect.res.getString("CustomerNo"));
                
                Cell dataaCell = dataRow.createCell(1);
                dataaCell.setCellValue(connect.res.getString("RevenueAmount"));
             }
            FileOutputStream fileOut = new FileOutputStream(new File("BudgetItems"));
            wb.write(fileOut);
            fileOut.close();
            System.out.println("done");
            
        } catch (Exception e) {
            System.out.println("ppppppppp");
        }


*/